# travis-ci does not support actionscript.
# However the build uses ant, which is usually used to build java projects.
# The ant task (mxmlc) provided by the flex SDK (ant/lib/flexTasks.jar) is used to build the project.
language: java
os: linux
dist: xenial
addons:
    apt:
      packages:
      - vnc4server
      - xfce4
      - ant
      - ant-optional
      - xfonts-base

jdk: openjdk8

before_install:
  # So flexunit can find the player and the ant build file does not have to be modified
  - sudo cp build-dep/bin/flashplayer /usr/local/bin/gflashplayer

install:
  # start a VNC session, this will be the desktop for tests
  - Xvnc :1 &
 
script:
    # this is where the build happens. A separate build is started for every entry in the matrix element
  - travis_wait ant $BUILD

env:
  global:
    # tell the build file where to find the flex SDK
    - FLEX_HOME="build-dep/bin/flex/"
    # this is to trick the flash player into thinking it is running on a desktop
    - DISPLAY=":1"
  jobs:
    # different configurations that should be built
    - BUILD="release"
    - BUILD="debug"

# Just so Travis.CI won't complain about Vanilla+ failing, since V+ wasn't intended to use Travis.
branches:
  except:
    VanillaPlus