package classes.lists 
{
	import classes.GlobalFlags.kFLAGS;
	/**
	 * Class for flag lists
	 * @since August 01, 2018
	 * @author Stadler76
	 */
	public class FlagLists 
	{
		public static const KEEP_ON_ASCENSION:Array = [
			kFLAGS.NEW_GAME_PLUS_LEVEL,
			kFLAGS.GAME_DIFFICULTY,
			kFLAGS.HUNGER_ENABLED,
			kFLAGS.HARDCORE_MODE,
			kFLAGS.HARDCORE_SLOT,
			kFLAGS.MRAPIER_BOUGHT,
			kFLAGS.LEGACY_RACIAL_STATS_ENABLED,
		];
		
		public static const KEEP_ON_ASCENSION_ETHERAL_CABIN:Array = [
			kFLAGS.CABIN_ETHERALIZED,
			kFLAGS.CAMP_CABIN_PROGRESS,
			kFLAGS.CAMP_BUILT_CABIN,
			kFLAGS.CAMP_CABIN_FURNITURE_BED,
			kFLAGS.CAMP_CABIN_FURNITURE_BOOKSHELF,
			kFLAGS.CAMP_CABIN_FURNITURE_CHAIR1,
			kFLAGS.CAMP_CABIN_FURNITURE_CHAIR2,
			kFLAGS.CAMP_CABIN_FURNITURE_DESK,
			kFLAGS.CAMP_CABIN_FURNITURE_DESKCHAIR,
			kFLAGS.CAMP_CABIN_FURNITURE_DRESSER,
			kFLAGS.CAMP_CABIN_FURNITURE_NIGHTSTAND,
			kFLAGS.CAMP_CABIN_FURNITURE_TABLE
		];
	}
}
